twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        cartservice: "@App\\Service\\CartService"

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_5_layout.html.twig']
